import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AudioProvider } from "@/context/AudioContext";
import { JobDescriptionProvider } from "@/context/JobDescriptionContext";
import { ResumeProvider } from "@/context/ResumeContext";
import { InterviewProvider } from "@/context/InterviewContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LockIntern",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AudioProvider>
          <JobDescriptionProvider>
            <ResumeProvider>
              <InterviewProvider>{children}</InterviewProvider>
            </ResumeProvider>
          </JobDescriptionProvider>
        </AudioProvider>
      </body>
    </html>
  );
}
